//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLink
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlayerDBEntities : DbContext
    {
        public PlayerDBEntities()
            : base("name=PlayerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GamerStyle> GamerStyles { get; set; }
        public virtual DbSet<Platform> Platforms { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
    }
}
