//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int PlayerId { get; set; }
        public string GamerName { get; set; }
        public int GameID { get; set; }
        public int GamerStyleID { get; set; }
        public int RegionID { get; set; }
        public int PlatformID { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual GamerStyle GamerStyle { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual Region Region { get; set; }
    }
}
